var shopscontent = '<h2 class="typing" id="heading">Dienstleister</h2><p style="margin-top: 20px" id="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><ul style="margin-top: 30px"><li id="bullet1">Lorem ipsum dolor</li><li id="bullet2">consectetur adipisicing elit</li><li id="bullet3">sed do eiusmod</li></ul><table id="sideBoxTable"><tr id="tabelHeading"><td>Anforderungen</td><td id="secondCell"></td></tr><tr><td class="caption">Sehr klein</td><td id="verysmall"></td></tr><tr><td class="caption">Klein</td><td id="small"></td></tr><tr><td class="caption">Mittelgroß</td><td id="medium"></td></tr><tr><td class="caption">Groß</td><td id="big"></td></tr><tr><td class="caption">Sehr groß</td><td id="verybig"></td></tr></table><div id="buttonWebseite" >Zur Webseite</div>'


var shops = {
    Shopify: {
        title: 'Shopify',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        angebunden: false,
        angebundenZukunft: false,
        url: 'https://www.shopify.de'
    },

    Shopware: {
        title: 'Shopware',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: '',
        small: '',
        medium: 'X',
        big: 'X',
        verybig: 'X',
    },
    Intershop: {
        title: 'Intershop',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    Oxid: {
        title: 'Oxid',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    Cosmoshop: {
        title: 'Cosmoshop',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    Magento: {
        title: 'Magento',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    Commercetools: {
        title: 'Commercetools',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    Modified: {
        title: 'Modified',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    Gambio: {
        title: 'Gambio',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    Woocommerce: {
        title: 'Woocommerce',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    Presta: {
        title: 'Presta',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    xtCommerce: {
        title: 'xtCommerce',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    Lightspeed: {
        title: 'Shopify',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    OScommerce: {
        title: 'OScommerce',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    einsundeins: {
        title: '1und1',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },
    Epages: {
        title: 'Epages',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        bullet1: 'Lorem ipsum dolor',
        bullet2: 'Lorem ipsum dolor',
        bullet3: 'Lorem ipsum dolor',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
    },

}
