var shopscontent = '<h2 class="typing" id="heading">Dienstleister</h2><h4 style="color: rgb(144, 144, 144)" class="typing" id="type">Keine Service Zuordnung</h4><p style="margin-top: 20px" id="text"></p><ul style="margin-top: 30px"><li id="bullet1"></li><li id="bullet2">consectetur adipisicing elit</li><li id="bullet3">sed do eiusmod</li></ul><table id="sideBoxTable"><tr id="tabelHeading"><td>Anforderungen</td><td id="secondCell"></td></tr><tr><td class="caption">Sehr klein</td><td id="verysmall"></td></tr><tr><td class="caption">Klein</td><td id="small"></td></tr><tr><td class="caption">Mittelgroß</td><td id="medium"></td></tr><tr><td class="caption">Groß</td><td id="big"></td></tr><tr><td class="caption">Sehr groß</td><td id="verybig"></td></tr></table><div id="buttonWebseite" >Zur Webseite</div>'


var shops = {
    Shopify: {
        title: 'Shopify',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        angebunden: false,
        angebundenZukunft: false,
        Servicetype: '',
        url: 'https://www.shopify.de'
    },

    Shopware: {
        title: 'Shopware',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: '',
        small: '',
        medium: 'X',
        big: 'X',
        verybig: 'X',
        Servicetype: '',
    },
    Intershop: {
        title: 'Intershop',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Oxid: {
        title: 'Oxid',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Cosmoshop: {
        title: 'Cosmoshop',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Magento: {
        title: 'Magento',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Commercetools: {
        title: 'Commercetools',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Modified: {
        title: 'Modified',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Gambio: {
        title: 'Gambio',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Woocommerce: {
        title: 'Woocommerce',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Presta: {
        title: 'Presta',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    xtCommerce: {
        title: 'xtCommerce',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Lightspeed: {
        title: 'Shopify',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    OScommerce: {
        title: 'OScommerce',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    einsundeins: {
        title: '1und1',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Epages: {
        title: 'Epages',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Azoo: {
        title: 'Azoo',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Jimdo: {
        title: 'Jimdo',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Serverspot: {
        title: 'Serverspot',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
    Versacommerce: {
        title: 'Versacommerce',
        text: '',
        bullet1: '',
        bullet2: '',
        bullet3: '',
        verysmall: 'X',
        small: 'X',
        medium: 'X',
        big: 'X',
        verybig: ' ',
        Servicetype: '',
    },
}
